version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - THREADS_API_SECRET=${THREADS_API_SECRET}
      - THREADS_APP_ID=${THREADS_APP_ID}
      - THREADS_APP_SECRET=${THREADS_APP_SECRET}
      - THREADS_REDIRECT_URI=${THREADS_REDIRECT_URI}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - THREADS_SSL_CERT_FILEPATH=${THREADS_SSL_CERT_FILEPATH}
      - THREADS_SSL_KEY_FILEPATH=${THREADS_SSL_KEY_FILEPATH}
    networks:
      - app-network

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - API_BASE_URL=${API_BASE_URL}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_BOTNAME=${TELEGRAM_BOTNAME}
      - ALLOWED_USERS=${ALLOWED_USERS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - app-network
    depends_on:
      - api

networks:
  app-network:
    driver: bridge