services:
  api:
    build: 
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - API_KEY=${API_KEY}
      - API_PUBLIC_URL=${API_PUBLIC_URL}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - AI_MODEL_NAME=${AI_MODEL_NAME}
      - THREADS_API_SECRET=${THREADS_API_SECRET}
      - THREADS_APP_ID=${THREADS_APP_ID}
      - THREADS_APP_SECRET=${THREADS_APP_SECRET}
      - THREADS_REDIRECT_URI=${THREADS_REDIRECT_URI}
      - TWITTER_CLIENT_ID=${TWITTER_CLIENT_ID}
      - TWITTER_CLIENT_SECRET=${TWITTER_CLIENT_SECRET}
      - TWITTER_REDIRECT_URI=${TWITTER_REDIRECT_URI}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - REDIS_URL=${REDIS_URL}
      - CHAT_HISTORY_TTL_SECONDS=${CHAT_HISTORY_TTL_SECONDS}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
      - THREADS_SSL_CERT_FILEPATH=${THREADS_SSL_CERT_FILEPATH}
      - THREADS_SSL_KEY_FILEPATH=${THREADS_SSL_KEY_FILEPATH}
      - TELEGRAM_BOTNAME=${TELEGRAM_BOTNAME}
    networks:
      - app-network

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    environment:
      - API_KEY=${API_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - API_PUBLIC_URL=${API_PUBLIC_URL}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_BOTNAME=${TELEGRAM_BOTNAME}
      - ALLOWED_USERS=${ALLOWED_USERS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - app-network
    depends_on:
      - api

networks:
  app-network:
    driver: bridge