# fly.toml app configuration file generated for telepost on 2025-01-26T09:15:30+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'telepost-bot'
primary_region = 'fra'

[build]
  dockerfile = 'bot/Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  processes = ['app']

[env]
  PORT = 8080
  API_PUBLIC_URL = "https://telepost-api.fly.dev"
  TELEGRAM_BOTNAME = "xpostmanbot"
  ALLOWED_USERS = "kikoems"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256